[package]
name = "orb-software-demos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3", default-features = false, features = ["tokio"] }
tokio = { version = "1", features = ["full", "sync"] }
url = "2.2"
serde = { version = "1.0", features = ["derive"]}
serde_with = { version = "2.1", features=["base64"]}
serde_json = "~1.0"
data-encoding = "2.3"
ring = "0.16"
thiserror = "1.0"
futures = "0.3"
lazy_static = "1.4"
event-listener = "*"
eyre = "0.6"
tracing = "0.1"
atty = "0.2"
tracing-subscriber = { version = "0.3", features = ["registry"] }
tracing-journald = "0.3"

[dependencies.reqwest]
version = "0.11.4"
features = ["blocking", "json", "multipart", "native-tls"]
