[package]
name = "update-verifier"
version = "0.1.0"
authors = [
    "Mark Eder <56895722+mrkdir@users.noreply.github.com>",
]
edition = "2021"
description = """
Checks general system health and manages the slot and rootfs state of the Orb.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
libc = "0.2.137"
serde = { version = "1.0.147", features = ["derive"] }
tap = "1.0.1"
tracing = "0.1.37"
tracing-journald = "0.3.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[dependencies.reqwest]
version = "0.11.4"
default-features = false
features = ["blocking", "json"]

[dependencies.slot-ctrl]
version = "0.1.0"
git = "ssh://git@github.com/worldcoin/orb-slot-ctrl"
tag = "v0.1.0"
