[package]
name = "orb-short-lived-token-daemon"
version = "0.2.6"
edition = "2021"
description = "A daemon for fetching backend access token"
authors = ["Tools For Humanity <info@worlcoin.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3.10", default-features = false, features = ["tokio"] }
tokio = { version = "1", features = ["full", "sync"] }
url = "2.2"
serde = { version = "1.0", features = ["derive"]}
serde_with = { version = "3.2", features=["base64"]}
serde_json = "~1.0"
data-encoding = "2.3"
ring = "0.16"
thiserror = "1.0"
futures = "0.3"
lazy_static = "1.4"
event-listener = "*"
eyre = "0.6"
tracing = "0.1"
atty = "0.2"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter", "std"] }
tracing-journald = "0.3"
const_format = "0.2"

[build-dependencies]
vergen = "7.5"
anyhow = "1.0"

[dev-dependencies]
wiremock = "0.5"
tempfile = "3.3"
serial_test = "2.0"

[dependencies.reqwest]
version = "0.11.4"
features = ["json", "multipart", "native-tls-vendored"]

[features]
default = []
prod = [] # use prod backend

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = [
        { unit-name = "worldcoin-short-lived-token-daemon" },
        { unit-name = "worldcoin-short-lived-token-dumb-client" }
    ]

[[bin]]
name = "orb-short-lived-token-daemon"
path = "src/daemon.rs"

[[bin]]
name = "orb-short-lived-token-dumb-client"
path = "src/dumb_client.rs"
