[package]
name = "thermal-util"
version.workspace = true  
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
color-eyre.workspace = true
seek-camera.workspace = true
owo-colors = "3"

