[package]
name = "orb-supervisor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
libc = "0.2.126"
listenfd = "1.0.0"
orb-mcu-schema = { path = "../orb-mcu-schema" }
prost = "0.10.4"
tokio = { version = "1.19.2", features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = "0.1.9"
tracing = { version = "0.1.35", features = ["attributes"] }
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
zbus = { version = "2.3.1", default-features = false, features = ["tokio"] }
zbus_systemd = { version = "0.0.4", features = ["systemd1"] }
thiserror = "1.0.31"
futures = "0.3.21"
once_cell = "1.13.0"

[dev-dependencies]
dbus-launch = "0.2.0"
tokio = { version = "1.19.2", features = ["sync", "test-util"] }
