[package]
name = "seek-camera"
version = "0.0.0"
edition = "2021"

[dependencies]
seek-camera-sys.path = "../sys"

log = "0.4"
fixed = "1.23.1"
bytemuck = { version = "1.13.1", features = ["derive"] }
