name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable
      - name: toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: format
        run: |
          cargo fmt -- --check
      - name: clippy
        run: |
          cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable  
      - name: toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: test
        run: |
          cargo test --all

  build:
    runs-on: ubuntu-22.04
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - name: toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable 
          rustup target add aarch64-unknown-linux-gnu
          cargo install cargo-zigbuild --force # --force used to not abort build if already installed (cached)
      - name: toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: build
        run: |
          cargo zigbuild --release --target aarch64-unknown-linux-gnu.2.27
      - name: prepare artifacts
        run: |
          mkdir artifacts && cp target/aarch64-unknown-linux-gnu/release/slot-ctrl artifacts/slot-ctrl
      - name: prepare debian package
        run: |
          mkdir -p .debpkg/usr/bin
          cp target/aarch64-unknown-linux-gnu/release/slot-ctrl .debpkg/usr/bin/slot-ctrl
          chmod +x .debpkg/usr/bin/slot-ctrl
      - uses: actions/upload-artifact@v2
        with:
          name: slot-ctrl-bin
          path: artifacts
      - uses: jiro4989/build-deb-action@v2
        # if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        with:
          package: slot-ctrl
          package_root: .debpkg
          maintainer: mrkdir
          version: 1.0.0 # ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'arm64'
          desc: 'This tool is designed to read and write the slot and rootfs state of the Orb.'
