name: Main CI
on:
  pull_request:
  push:
    branches:
      - main
      - prod
    tags:
      - "*"

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check --all

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Clippy lints
        run: cargo clippy --all --all-features --all-targets --no-deps

  doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cargo Doc
        run: cargo doc --all --all-features --no-deps --document-private-items

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cargo Test
        run: cargo test --all --all-features --all-targets

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11
      - run: zig version
      - name: Install cargo-zigbuild
        run: cargo install --version 0.17.0 cargo-zigbuild

      - name: Cargo Zigbuild
        run: cargo test --all --all-features --all-targets
      - name: Cargo build
        run: cargo zigbuild --all --all-features --

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check licenses and security advisories
        uses: EmbarkStudios/cargo-deny-action@v1
