name: "CI"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '*'

jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable
      - name: toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: format
        run: |
          cargo fmt -- --check
      - name: clippy
        run: |
          cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable  
      - name: toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: test
        run: |
          cargo test --all

  build:
    runs-on: ubuntu-22.04
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - name: toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable 
          rustup target add aarch64-unknown-linux-gnu
          cargo install cargo-zigbuild --force # --force used to not abort build if already installed (cached)
      - name: toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: build
        run: |
          cargo zigbuild --release --target aarch64-unknown-linux-gnu.2.27
      - name: Cache binary
        uses: actions/cache@v3
        with:
          path: target/aarch64-unknown-linux-gnu/release/slot-ctrl
          key: slot-ctrl
