name: Continuous integration


on:
  push:
    branches: [ "main" ]
    tags:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - run: |
          git config --global --add url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "ssh://git@github.com/worldcoin/"
          git config --global --add url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "git@github.com:worldcoin/"
          git config --global --add url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "https://github.com/worldcoin/"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@1.64.0
      - run: cargo test

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "ssh://git@github.com/worldcoin/"
          git config --global url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "git@github.com:worldcoin/"
          git config --global url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "https://github.com/worldcoin/"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@1.64.0
        with:
          components: clippy
      - run: cargo clippy -- -D warnings -W clippy::pedantic

  deb:
    strategy:
      matrix:
        flavor: [prod, stage]
        include:
          - flavor: prod
            cargo_deb_opts: "--release --features=prod"
          - flavor: stage
            cargo_deb_opts: ""
    # Ubuntu version should match the version of Jetson-docker, because libc in toolchain should match
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - run: |
          git config --global --add url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "ssh://git@github.com/worldcoin/"
          git config --global --add url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "git@github.com:worldcoin/"
          git config --global --add url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "https://github.com/worldcoin/"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
      - run: |
          sudo apt-get -y update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu
        env:
          DEBIAN_FRONTEND: noninteractive
      - uses: dtolnay/rust-toolchain@1.64.0
        with:
          targets: aarch64-unknown-linux-gnu
          toolchain: stable
      - run: cargo install cargo-deb || echo OK
      - uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          use-cross: true
          command: deb
          args: --target aarch64-unknown-linux-gnu -o orb-short-lived-token-daemon-${{ matrix.flavor }}.deb -- ${{ matrix.cargo_deb_opts }}

      - uses: actions/upload-artifact@v3
        with:
          name: orb_short_lived_token_daemon_${{ matrix.flavor }}
          path: orb-short-lived-token-daemon-${{ matrix.flavor }}.deb
          if-no-files-found: error

  release:
    needs: deb
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Create a latest release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GIT_HUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          files: |
            */*.deb

      - name: Create an actual release latest release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GIT_HUB_TOKEN }}"
          prerelease: false
          files: |
            */*.deb
