name: Release
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
            git config --global url."https://${{ secrets.RUNNER_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "ssh://git@github.com/worldcoin/"
            git config --global url."https://${{ secrets.RUNNER_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "git@github.com:worldcoin/"
            git config --global url."https://${{ secrets.RUNNER_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "https://github.com/worldcoin/"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RUNNER_TOKEN }}
          submodules: recursive
      - name: Install zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - uses: dtolnay/rust-toolchain@1.61.0
        with:
          targets: aarch64-unknown-linux-gnu
      - run: cargo install cargo-zigbuild
      - name: Build orb-supervisor binary
        run: cargo zigbuild --release --target aarch64-unknown-linux-gnu.2.27 -p orb-supervisor
      - name: Cache orb-supervisor binary
        uses: actions/cache@v3
        with:
          path: target/aarch64-unknown-linux-gnu/release/orb-supervisor
          key: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-orb-supervisor-bin

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve cache
        id: cache
        uses: actions/cache@v3
        with:
          path: target/aarch64-unknown-linux-gnu/release/orb-supervisor
          key: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-orb-supervisor-bin
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v3
        with:
          name: orb-supervisor
          path: target/aarch64-unknown-linux-gnu/release/orb-supervisor
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Archive binary
        shell: bash
        run: |
          cd target/aarch64-unknown-linux-gnu/release          
          tar cvzf orb-supervisor-${{ steps.tag.outputs.tag }}.tar.gz orb-supervisor
          shasum -a 256 orb-supervisor-${{ steps.tag.outputs.tag }}.tar.gz > orb-supervisor-${{ steps.tag.outputs.tag }}.tar.gz.tar.gz.sha256
          cd -
      - name: Make a github release from the binary
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/aarch64-unknown-linux-gnu/release/orb-supervisor*.tar.gz
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          generate_release_notes: true
