name: Release library
on:
  push:
    tags:
      - orb-supervisor-[a-z]+-[0-9]+.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@727a6f0a561be04e09013531e73a3983a65e3479 # pin@v1
      - name: Read tag prefix
        id: prefix
        shell: bash
        run: |
          [[ ${{ steps.tag.outputs.tag }} =~ ^(orb-supervisor-[a-z]+).* ]] && echo "::set-output name=prefix::${BASH_REMATCH[1]}"
      - name: Install changelog parser
        uses: taiki-e/install-action@f863cdaef3a8e79111b7a8c74d466b89d31d2fdc # pin@parse-changelog
      - name: Read changelog contents
        id: changelog
        shell: bash
        run: |
          echo 'TITLE<<EOF' >> $GITHUB_ENV
          parse-changelog -t ${{ steps.prefix.outputs.prefix }}/CHANGELOG.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo 'NOTES<<EOF' >> $GITHUB_ENV
          parse-changelog ${{ steps.prefix.outputs.prefix }}/CHANGELOG.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Make a github release for the library
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v1
        with:
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          name: ${{ steps.prefix.outputs.prefix }} ${{ env.TITLE }}
          body: ${{ env.NOTES }}
